; fibonacci
        PUSH 1
        DUP

:LOOP   DUP
        DUP 2
        ADD
        DUP
        PUSH -0x7FFFFF
        CMP
        JMPLT loop
        HALT
        ; PUSH 'a'
;         JMP TOP
        ; NOOP TOP
        ; NOOP TOP
        ; NOOP TOP
        ; NOOP TOP
        ; NOOP TOP
        ; NOOP TOP
        ; NOOP TOP
        ; NOOP TOP
        ; NOOP TOP
        ; NOOP TOP
        ; NOOP TOP
        ; NOOP TOP
        ; NOOP TOP
        ; NOOP TOP
        ; NOOP TOP
        ; NOOP TOP
        ; NOOP TOP
        ; NOOP TOP
        ; NOOP TOP
        ; NOOP TOP
        ; NOOP TOP
        ; NOOP TOP
        ; NOOP TOP
        ; NOOP TOP
        ; NOOP TOP
        ; NOOP TOP
        ; NOOP TOP
        ; NOOP TOP
        ; NOOP TOP
        ; NOOP TOP
        ; NOOP TOP
        ; NOOP TOP
        ; NOOP TOP
        ; NOOP TOP
        ; NOOP TOP
        ; NOOP TOP
        ; NOOP TOP
        ; NOOP TOP
        ; NOOP TOP
        ; NOOP TOP
        ; NOOP TOP
        ; NOOP TOP
        ; NOOP TOP
        ; NOOP TOP
        ; NOOP TOP
        ; NOOP TOP
        ; NOOP TOP
        ; NOOP TOP
        ; NOOP TOP
        ; NOOP TOP
        ; NOOP TOP
        ; NOOP TOP
        ; NOOP TOP
        ; NOOP TOP
        ; NOOP TOP
        ; NOOP TOP
        ; NOOP TOP
        ; NOOP TOP
        ; NOOP TOP
        ; NOOP TOP
        ; NOOP TOP
        ; NOOP TOP
        ; NOOP TOP
        ; NOOP TOP
        ; NOOP TOP
        ; NOOP TOP
        ; NOOP TOP
        ; NOOP TOP
        ; NOOP TOP
        ; NOOP TOP
        ; NOOP TOP
        ; NOOP TOP
        ; NOOP TOP
        ; NOOP TOP
        ; NOOP TOP
        ; NOOP TOP
        ; NOOP TOP
        ; NOOP TOP
        ; NOOP TOP
        ; NOOP TOP
        ; NOOP TOP
        ; NOOP TOP
        ; NOOP TOP
        ; NOOP TOP
        ; NOOP TOP
        ; NOOP TOP
        ; NOOP TOP
        ; NOOP TOP
        ; NOOP TOP
        ; NOOP TOP
        ; NOOP TOP
        ; NOOP TOP
        ; NOOP TOP
        ; NOOP TOP
        ; NOOP TOP
        ; NOOP TOP
        ; NOOP TOP
        ; NOOP TOP
        ; NOOP TOP
        ; NOOP TOP
        ; NOOP TOP
        ; NOOP TOP
        ; NOOP TOP
        ; NOOP TOP
        ; NOOP TOP
        ; NOOP TOP
        ; NOOP TOP
        ; NOOP TOP
        ; NOOP TOP
        ; NOOP TOP
        ; NOOP TOP
        ; NOOP TOP
        ; NOOP TOP
        ; NOOP TOP
        ; NOOP TOP
        ; NOOP TOP
        ; NOOP TOP
        ; NOOP TOP
        ; NOOP TOP
        ; NOOP TOP
        ; NOOP TOP
        ; NOOP TOP
        ; NOOP TOP
        ; NOOP TOP
        ; NOOP TOP
        ; NOOP TOP
        ; NOOP TOP
        ; NOOP TOP
        ; NOOP TOP
        ; NOOP TOP
        ; NOOP TOP
        ; NOOP TOP
        ; NOOP TOP
        ; NOOP TOP
        ; NOOP TOP
        ; NOOP TOP
        ; NOOP TOP
        ; NOOP TOP
        ; NOOP TOP
        ; NOOP TOP
        ; NOOP TOP
        ; NOOP TOP
        ; NOOP TOP
        ; NOOP TOP
        ; NOOP TOP
        ; NOOP TOP
        ; NOOP TOP
        ; NOOP TOP
        ; NOOP TOP
        ; NOOP TOP
        ; NOOP TOP
        ; NOOP TOP
        ; NOOP TOP
        ; NOOP TOP
        ; NOop top
        ;Noop penis